# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f535435ec2e24b108c7bb33998e5022b6bb1f428ad44070bd01a4a9605dcbc2be3bde993c82cc3499ee937b82f3ad67e25faf3c4b1f14a594a55646c7a981c0d

test:
  secret_key_base: 22f81fe8bebb0832190781b93f5d59fc3b1ad81817272d6113d86eab79d2accb0da3d2f5188a9b66f8a5b713e327651dd7fce222966dc92218e424b2a76f605c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
