# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b3061f2c1bfe2e2b8bc88c05099b4d55ae9041b57041a4413c310dfd9a0709abe53bc7f4d62219cc8f3ca07c4c433ed1d40407342d7c46cb158f60065400518

test:
  secret_key_base: 86b58288263647ca1db761b5c4261465543b6bb99ae43ee6c4b682d9d2279eecc1a11a4332511f7188440a3779569d3bf4f2308de9a3601e74d75493d83c655d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
